/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhopoo.UI;

import javax.swing.JOptionPane;
import trabalhopoo.Controlador.Controlador;

/**
 *
 * @author david
 */
public class CadastroSubstituto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroSubstituto
     */
    public CadastroSubstituto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        botaoDoutorado = new javax.swing.JRadioButton();
        botaoDoze = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        botao24 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botaoS1 = new javax.swing.JRadioButton();
        botaoGraduacao = new javax.swing.JRadioButton();
        botaoTitular = new javax.swing.JRadioButton();
        botaoS3 = new javax.swing.JRadioButton();
        botaoMestrado = new javax.swing.JRadioButton();
        botaoLivre = new javax.swing.JRadioButton();
        botaoS2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtDepartamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup2.add(botaoDoutorado);
        botaoDoutorado.setText("Doutorado");

        buttonGroup3.add(botaoDoze);
        botaoDoze.setText("12 Horas");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(botao24);
        botao24.setText("24 Horas");

        jLabel2.setText("Nome do Docente:");

        jLabel4.setText("Salário do Docente:");

        jLabel3.setText("Código do Docente:");

        jLabel1.setText("Titulação Do Docente:");

        jLabel5.setText("Nível do Docente:");

        buttonGroup1.add(botaoS1);
        botaoS1.setText("S1");
        botaoS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoS1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(botaoGraduacao);
        botaoGraduacao.setText("Graduação");

        buttonGroup2.add(botaoTitular);
        botaoTitular.setText("Titular");

        buttonGroup1.add(botaoS3);
        botaoS3.setText("S3");

        buttonGroup2.add(botaoMestrado);
        botaoMestrado.setText("Mestrado");

        buttonGroup2.add(botaoLivre);
        botaoLivre.setText("Livre Docente");

        buttonGroup1.add(botaoS2);
        botaoS2.setText("S2");
        botaoS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoS2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Carga Horaria do Docente:");

        jLabel7.setText("Departamento do Docente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botaoMestrado)
                                            .addComponent(botaoGraduacao)
                                            .addComponent(botaoDoutorado))
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(botaoDoze))
                                    .addComponent(jLabel5))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoTitular)
                                    .addComponent(botaoLivre)
                                    .addComponent(botao24))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoS1)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoS2)
                                        .addGap(11, 11, 11)
                                        .addComponent(botaoS3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtSalario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoS1)
                    .addComponent(botaoS2)
                    .addComponent(botaoS3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoGraduacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoMestrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoDoutorado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoLivre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoTitular)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDoze)
                    .addComponent(botao24))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoS1ActionPerformed

    private void botaoS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoS2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean podeCadastrar = true;
        String nivel = null, titulacao = null;
        int cargaHoraria = 0;
        Controlador control = new Controlador();
        
        if(txtNome.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Nome do Docente!");
            txtNome.requestFocus();
            podeCadastrar = false;
        }
        if(txtCodigo.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Código do Docente!");
            txtCodigo.requestFocus();
            podeCadastrar = false;
        }
        if(txtSalario.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Salario do Docente!");
            txtSalario.requestFocus();
            podeCadastrar = false;
        }
        if(txtDepartamento.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Insira o Departamento do Docente!");
            txtDepartamento.requestFocus();
            podeCadastrar = false;
        }
        if(botaoS1.isSelected()){
            nivel = "S1";
        }else if(botaoS2.isSelected()){
            nivel = "S2";
        }else if(botaoS3.isSelected()){
            nivel = "S3";
        }else{
            JOptionPane.showMessageDialog(this, "Insira o Nivel do Docente!");
            podeCadastrar = false;
        }    
        if(botaoGraduacao.isSelected()){
            titulacao = "Graduação";
        }else if(botaoMestrado.isSelected()){
            titulacao = "Mestrado";
        }else if(botaoDoutorado.isSelected()){
            titulacao = "Doutorado";
        }else if(botaoLivre.isSelected()){
            titulacao = "Livre Docência";
        }else if(botaoTitular.isSelected()){
            titulacao = "Titular";
        }else{
            JOptionPane.showMessageDialog(this, "Insira a Titulação do Docente!");
            podeCadastrar = false;  
        }
        if(botaoDoze.isSelected()){
            cargaHoraria = 12;
        }else if(botao24.isSelected()){
            cargaHoraria = 24;
        }else{
            JOptionPane.showMessageDialog(this, "Insira a Carga Horaria do Docente!");
            podeCadastrar = false;
        }
        if(podeCadastrar==true && control.existeDepartamento(txtDepartamento.getText())){
            control.addSubstituto(txtDepartamento.getText(), txtCodigo.getText(), txtNome.getText(), Float.parseFloat(txtSalario.getText()), nivel, titulacao, cargaHoraria);
            txtNome.setText("");
            txtCodigo.setText("");
            txtSalario.setText("");
            txtDepartamento.setText("");
            JOptionPane.showMessageDialog(this, "Cadastro do Docente realizado com Sucesso!");            
        }else{
            JOptionPane.showMessageDialog(this, "Departamento Inexistente!");            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroSubstituto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroSubstituto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botao24;
    private javax.swing.JRadioButton botaoDoutorado;
    private javax.swing.JRadioButton botaoDoze;
    private javax.swing.JRadioButton botaoGraduacao;
    private javax.swing.JRadioButton botaoLivre;
    private javax.swing.JRadioButton botaoMestrado;
    private javax.swing.JRadioButton botaoS1;
    private javax.swing.JRadioButton botaoS2;
    private javax.swing.JRadioButton botaoS3;
    private javax.swing.JRadioButton botaoTitular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
